#%RAML 1.0
title: compress-decompress-json-api

traits:
  successTrait: !include traits/success-trait.raml
  errorTrait: !include traits/error-trait.raml

/compress:
  description: Compress payload and store to the local dir
  post:
    is: [successTrait, errorTrait]
    headers:
      content-type:
        type: string
        required: true
        example: "application/json"
    body:
      application/json:

/decompress:
  description: Decompress payload and store to the local dir
  post:
    is: [successTrait, errorTrait]
    headers:
      content-type:
        type: string
        required: true
        example: "application/zip"
    body:
      application/zip: