#%RAML 1.0
title: employees-api

traits:
  errorTrait: !include traits/error-trait.raml
  successTrait: !include traits/success-trait.raml

/employees:
  post:
    description: Create employees from JSON payload
    is: [successTrait, errorTrait]
    headers:
      content-type:
        required: true
        type: string
        example: "application/json"
    body:
      multipart/form-data:
      application/octet-stream:
      application/zip:
      application/json:
        type: !include /ref/employees-schema.json
        example: !include /ref/employees-example.json
